审核字幕
udacity-china-translation/srt-translation-2017-07-YouShareRose pull request #2
Opened 2017-07-29 06:01 UTC by YouShareRose

@ivylee0919  对原来的字幕没有做什么修改，只是在有两处人名之前添加了空格

2017-07-29 06:29 UTC, ivylee0919 requested changes
有格式错误的地方不止这两处，还能找到其他的地方吗？对照英文字幕和视频，现在的中文字幕有很多表达不通顺的地方，尝试修改下？ 🤓 


**提示：**

- [字幕格式规范](http://discussions.youdaxue.com/t/v1-1/3313)里面，英文字幕里面的这个符号 >> 翻译为中文字幕的时候要用什么符号呢？
- 中英文之间加空格，除了这两处人名，还有一处中英文之间没有加空格
- 数字与中文之间也应该有空格
- 校对的时候，可以问自己：如果用这个中文字幕+视频，我能明白她们要表达的东西吗？ 🤔

2017-07-29 07:08 UTC, YouShareRose commented
如果一条字幕中只有一个人说话，>> 可直接删去。
这种情况下还需要输入“— ”​吗？
如果是
9
00:00:27,160 --> 00:00:29,840
the highest paid person's opinion
>> In this course,
这种情况，需要把第二行的“>>” 替换为“— ”​，在上面的一行没有说话人变更，是不是不用加上“— ”​？

2017-07-29 07:25 UTC, ivylee0919 commented
9
00:00:27,160 --> 00:00:29,840
the highest paid person's opinion
>> In this course
这种情况，需要把后半句的“>>” 替换为“— ”​，前面不用多添加一条“— ”​

关于短横线的符号，我比较倾向于直接将 “>>” 替换为“— ”​，除非英文的符号标记位置不正确。
我去更新下字幕规范！感谢提出 👍

2017-07-29 09:29 UTC, YouShareRose commented
@ivylee0919 重新审核了一遍，不过上面还有一些我不理解的地方

- businesses who have an online presence via websites or mobile apps 
这里的翻译不确定

- the processing culture, needed to facilitate data driven decisions
不理解 processing culture 的意思

- how to design and analyze experiments for a bus decision making
 不理解 a bus decision making 的意思

2017-07-29 13:09 UTC, ivylee0919 commented
这个英文字幕的质量比较低，使得校对难度增大，你这次校对的很棒！👍
我发现你不理解的地方似乎都是英文字幕有误。
通常遇到这种情况，我会去 youtube 上查看[对应的视频](https://www.youtube.com/watch?v=gR_buSP6sdw)（youtube 视频链接可以在任务表中找到），播放时使用英文（自动生成）字幕，可以识别一些明显的英文字幕错误
![qq 20170729210149](https://user-images.githubusercontent.com/11519486/28745052-288af228-74a2-11e7-960e-0750c0a5a253.png)
刚刚把这个英文字幕校对了一下，你看看现在是不是好理解了？
再对照这个校对后的英文字幕修改下？加油！ 💪

2017-07-29 13:27 UTC, ivylee0919 requested changes
有时校对比翻译还要难，再加油修改一次！💪

2017-07-29 13:27 UTC, ivylee0919 commented on locales/zh-cn/gR_buSP6sdw.srt
句子末尾的空格要删掉

2017-07-29 13:27 UTC, ivylee0919 commented on locales/zh-cn/gR_buSP6sdw.srt
这里根据听到的修改了一下英文，hippos 改为了 hipsters，试着翻译一下？

2017-07-29 13:27 UTC, ivylee0919 commented on locales/zh-cn/gR_buSP6sdw.srt
> +你的 A/B 测试框架
your using 改为了 or use an
对应修改下中文？

2017-07-29 13:27 UTC, ivylee0919 commented on locales/zh-cn/gR_buSP6sdw.srt
> +本课程会讲授如何设计任务 选择指标 并分析结果
顿号在这里是要保留的

2017-07-29 13:27 UTC, ivylee0919 commented on locales/zh-cn/gR_buSP6sdw.srt
> +我是计算机博士 我在 Google 工作了 12 年多
与上文相接的话，连续3个主语 *我*，似乎有点多？

2017-07-29 13:27 UTC, ivylee0919 commented on locales/zh-cn/gR_buSP6sdw.srt
> +包括基础架构、设计指标和 dashboard、
这里你听出了英文的错误，很棒！👍

2017-07-29 13:27 UTC, ivylee0919 commented on locales/zh-cn/gR_buSP6sdw.srt
> +运行并分析实验、
这部分以及以下部分的英文校对过了，可以再整体理解下

2017-07-29 13:27 UTC, ivylee0919 commented on locales/zh-cn/gR_buSP6sdw.srt
>  优达学城的开发人员 在此之前
这里应该是优达学城的课程开发者，也是英文错误

2017-07-30 05:13 UTC, YouShareRose commented on locales/zh-cn/gR_buSP6sdw.srt
我觉得它应该还是 hippo，是 the HIghest Paid Person's Opinion 的缩写，正好组成了单词河马。

2017-07-30 05:38 UTC, ivylee0919 commented on locales/zh-cn/gR_buSP6sdw.srt
你是对的！赞！👍👍👍
Get 了新知识 ，[HiPPO](http://whatis.techtarget.com/definition/HiPPOs-highest-paid-persons-opinions)

2017-08-01 01:28 UTC, YouShareRose commented
@ivylee0919  修改审核，the process and culture needed to facilitate data-driven decisions 这句还是有问题，不明白 process and culture 的意思

2017-08-01 07:18 UTC, YouShareRose commented
@ivylee0919 修改好了，麻烦再检查一下

2017-08-01 07:28 UTC, ivylee0919 approved these changes

2017-08-01 07:28 UTC, ivylee0919 commented
做的很棒，你通过了！ 💯

2017-08-01 07:29 UTC, merged